using System;
using PokemonProject.Entities;

namespace PokemonProject
{
    class Program
    {
        static void Main(string[] args)
        {

            Console.OutputEncoding = System.Text.Encoding.UTF8;
            // Cria a instância do jogo
            Game game = new Game();

            // Inicia o jogo
            game.StartGame();
        }
    }
}

// FICOU FALTANDO EXEMPLOS DE POO, NÃO TEVE HERANÇA, CONSEQUENTEMENTE TAMBÉM NÃO TEVE POLIMORFISMO.
// O PROJETO FICOU BEM CRIATIVO E O CODIGO ESTA ORGANIZADO COM A PROGRAM LIMPA
// A CLASSE POKEMON TEM UM EXEMPLO DE PROPRIEDADE NÃO ENCAPSULADA (HPNOW), SERIA INTERESSANTE COLOCAR UM MÉTODO PARA ALTERAR ESSE VALOR AO INVÉS DE DEIXAR O SET PÚBLICO.
// ATENTAR-SE PARA OS USINGS DESNECESSÁRIOS NAS CLASSES.
// ATENTAR-SE PARA NÃO MISTURAR PORTUGUÊS COM INGLÊS.
// BOM EXEMPLO DE HERANÇA SERIA TER UMA CLASSE ABSTRATA POKEMON COM AS REGRAS GENERICAS DE UM POKEMON E SUBCLASSES CONCRETAS PARA CADA ESPÉCIE E PROPRIEDADE.